import os
import datetime

# 获取当前时间 (UTC)
current_time = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

# 生成 HTML 内容
html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Daily Update</title>
</head>
<body>
    <h1>Daily News Update</h1>
    <p>Last updated: {current_time}</p>
    <hr>
    <p>This page is automatically generated by GitHub Actions.</p>
</body>
</html>
"""

# 将内容写入 index.html
file_path = "index.html"
with open(file_path, "w", encoding="utf-8") as f:
    f.write(html_content)

print(f"✅ 成功生成文件: {file_path}")
print(f"📄 文件内容预览: Last updated: {current_time}")